### ISSUE TITLE
Granular merging precedence for glyphs

### ISSUE THREAD

**Issue by RickyDaMa** [googlefonts/ufomerge#25]
For example, if I have UFO Foo that provides /a/b/c, and UFO Bar that provides /b/c/d, I would like to be able to choose to prefer /b from Foo but /c from Bar

Currently ufomerge always prioritises one of the UFOs over the other, not permitting this granular control

Encoding this information in an understandable way in commandline arguments could be a bit of a pain, maybe something like `--prefer-ufo{1,2}-for <glyph> ...`

**Comment by simoncozens** [comment]
I don't think this understanding is correct.

ufomerge always merges UFO2 into UFO1; the `glyphs` parameter tells you which glyphs to take from UFO2 into UFO1, so we already have this "granular preference"
