### ISSUE TITLE
Remove empty classes and lookups?

### ISSUE THREAD

**Issue by madig** [googlefonts/ufomerge#3]
A UFO I want to subset is later crashing feaLib with `Empty glyph class in contextual positioning rule`. Is there a particular reason why dropping empty lookups isn't implemented yet? Otherwise I'd try my hand at it.

**Comment by simoncozens** [comment]
I think I started - 0e12df4 and ca84892 are supposed to address this. But obviously I didn't get all of them...

**Comment by madig** [comment]
https://github.com/googlefonts/ufomerge/blob/257e339f0b3a8474de508aa4c288f6e163fd7e58/Lib/ufomerge/__init__.py#L488

Should this be `if not hasattr(feature, "statements"):`? Otherwise `ast.LookupBlock` get skipped over?
